services:
  stats-db:
    image: postgres:latest
    container_name: stats-db-container
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=stats-db
    volumes:
      - stats-db-data:/var/lib/postgresql/data
    command: ["postgres", "-c", "log_statement=all"]
    networks:
      - app_network2

  ewm-db:
    image: postgres:latest
    container_name: ewm-db-container
    ports:
      - "5433:5432"
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=main-db
    volumes:
      - ewm-db-data:/var/lib/postgresql/data
    networks:
      - app_network2

volumes:
  ewm-db-data:
  stats-db-data:
networks:
  app_network2:
    driver: bridge