server:
  port: 0

spring:
  application:
    name: aggregator
  retry:
    enabled: true

logging:
  level:
    ru.practicum.stats: TRACE
    org:
      springframework: ERROR
      appache.kafka: WARN

aggregator:
  kafka:
    producers:
      similarity-events:
        properties:
          bootstrap.servers: localhost:9092
          client.id: "stats.aggregator"
          key.serializer: org.apache.kafka.common.serialization.StringSerializer
          value.serializer: ru.practicum.kafka.serializer.GeneralAvroSerializer
          close-time: 15
          #########################
          linger.ms: 0
          batch.size: 16384
          request.timeout.ms: 10000
          delivery.timeout.ms: 15000
          max.block.ms: 10000
          retries: 1
        topics:
          - name: similarity-events
            value: stats.events-similarity.v1
    consumers:
      users-events:
        properties:
          group.id: "aggregator-client"
          bootstrap.servers: localhost:9092
          client.id: "interaction.aggregator"
          key.deserializer: org.apache.kafka.common.serialization.StringDeserializer
          value.deserializer: ru.practicum.kafka.serializer.UserActionDeserializer
          ########################
          enable-auto-commit: false
          close-time: 15
          session.timeout.ms: 10000
          heartbeat.interval.ms: 3000
          max.poll.interval.ms: 30000
          fetch.max.wait.ms: 500
          fetch.min.bytes: 1
          auto.offset.reset: earliest
          max.poll.records: 10
        topics:
          - name: users-events
            value: stats.user-actions.v1

ratings:
  view: 0.4
  register: 0.8
  like: 1