server:
  port: 0

spring:
  application:
    name: request-service
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  sql:
    init:
      mode: always
  datasource:
    driver-class-name: ${SPRING_DRIVER_CLASS_NAME:org.postgresql.Driver}
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/postgres}
    username: ${SPRING_DATASOURCE_USERNAME:admin}
    password: ${SPRING_DATASOURCE_PASSWORD:admin}
  main:
    allow-bean-definition-overriding: true

logging:
  level:
    org:
      springframework:
        orm:
          jpa: INFO
        transaction:
          interceptor: TRACE
      hibernate:
        SQL: DEBUG
        type: TRACE
        orm:
          jdbc:
            bind: TRACE