server:
  port: 0

grpc:
  server:
    port: 0

spring:
  application:
    name: analyzer
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  sql:
    init:
      mode: always
  datasource:
    driver-class-name: ${SPRING_DRIVER_CLASS_NAME:org.postgresql.Driver}
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/postgres}
    username: ${SPRING_DATASOURCE_USERNAME:admin}
    password: ${SPRING_DATASOURCE_PASSWORD:admin}
  main:
    allow-bean-definition-overriding: true

logging:
  level:
    org:
      hibernate.orm.jdbc.bind: TRACE
      hibernate.SQL: TRACE
      springframework:
        orm:
          jpa: INFO
          jpa.JpaTransactionManager: DEBUG
        transaction: INFO
        transaction.interceptor: TRACE
        web.filter.CommonsRequestLoggingFilter: DEBUG

analyzer:
  kafka:
    consumers:
      interaction:
        properties:
          group.id: "analyzer-interaction-client"
          bootstrap.servers: localhost:9092
          client.id: "stats.analyzer.interaction"
          key.deserializer: org.apache.kafka.common.serialization.StringDeserializer
          value.deserializer: ru.practicum.kafka.serializer.UserActionDeserializer
          enable.auto.commit: false
        topics:
          - name: users-actions
            value: stats.user-actions.v1
      similarity:
        properties:
          group.id: "analyzer-similarity-client"
          bootstrap.servers: localhost:9092
          client.id: "stats.analyzer.similarity"
          key.deserializer: org.apache.kafka.common.serialization.StringDeserializer
          value.deserializer: ru.practicum.kafka.serializer.SimilarityActionDeserializer
          enable.auto.commit: false
        topics:
          - name: events-similarity
            value: stats.events-similarity.v1

ratings:
  view: 0.4
  register: 0.8
  like: 1